const fs = require('fs');
const path = require('path');

// Gather all V8 JSON files generated by pytest-playwright
const v8Dir = path.join(__dirname, '.qa-runs', 'v8-coverage');
const v8List = [];
if (fs.existsSync(v8Dir)) {
    for (const file of fs.readdirSync(v8Dir)) {
        if (file.endsWith('.json')) {
            v8List.push(path.join(v8Dir, file));
        }
    }
}

module.exports = {
    name: 'Frontend V8 Coverage',
    outputDir: './.qa-runs/coverage-reports',
    reports: [
        ['v8'],
        ['lcovonly']
    ],
    entryFilter: {
        '**/public/js/**': true
    },
    sourceFilter: {
        '**/public/js/**': true
    },
    inputDir: v8Dir
};